version: "3.7"
services:
  web:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - "wildfly:wildfly.docker.local"
      - "frontend:frontend.docker.local"
    depends_on:
      - wildfly
      - frontend

  wildfly:
    restart: unless-stopped
    build: ./docker/wildfly/
    ports:
      - "9990:9990"
    links:
      - "db:db.docker.local"
    depends_on:
      - db

  frontend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend/:/home/docker/frontend/
      - ./dub-data/:/home/docker/.dub/
    user: ${CURRENT_UID}

  db:
    image: postgres:9.6.19-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: bolacha
      POSTGRES_USER: maria
      POSTGRES_PASSWORD: maria
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 10000:8080
    links:
      - "db:db.docker.local"
    depends_on:
      - db
